on: push

on: push
name: Validate
jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # Runs a single command using the runners shell
    - name: current directory
      run: pwd
    - name: test
      uses: desaintmartin/helm-kubeval-action@master
      with:
        path: ./jx/charts/jx/templates
